FROM lcr.loongnix.cn/openanolis/anolisos:23.1

RUN dnf install -y tzdata  >> /dev/null \
    && dnf clean all \
    && groupadd -r -g 10000 harbor && useradd --no-log-init -r -m -g 10000 -u 10000 harbor \
    && mkdir /harbor/
