FROM lcr.loongnix.cn/openanolis/anolisos:23.1

RUN dnf install -y python3 python3-pip python3-PyYAML python3-jinja2 && dnf clean all
RUN pip3 install pipenv==2022.1.8

#To install only htpasswd binary from photon package httpd
RUN dnf install -y rpm cpio apr-util openssl
RUN dnf -y --downloadonly --downloaddir=/tmp/ install httpd-tools && rpm2cpio /tmp/httpd-tools-*.rpm | cpio -ivdm ./usr/bin/htpasswd && rm -f /tmp/*
#RUN dnf -y --downloadonly --downloaddir=/tmp/ install httpd openssl httpd-tools && rpm2cpio /tmp/httpd-*.rpm | cpio -ivdm ./usr/bin/htpasswd && rm -f /tmp/*
