FROM lcr.loongnix.cn/openanolis/anolisos:23.1

RUN groupadd -g 999 redis \
    && useradd -u 999 -g 999 -c "Redis Database Server" -d /var/lib/redis -s /sbin/nologin -m redis
RUN dnf install -y redis && dnf clean all
