FROM lcr.loongnix.cn/openanolis/anolisos:23.1

RUN dnf install -y nginx >> /dev/null \
    && dnf clean all \
    && groupmod -g 10000 nginx && usermod -g 10000 -u 10000 -d /home/nginx -s /bin/bash nginx \
    && ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log
