FROM lcr.loongnix.cn/openanolis/anolisos:23.1

RUN dnf install httpd-tools -y &&  dnf clean all \
    && mkdir -p /etc/registry \
    && groupadd -r -g 10000 harbor && useradd --no-log-init -m -g 10000 -u 10000 harbor
