FROM lcr.loongnix.cn/library/golang:1.22

ENV DISTRIBUTION_DIR /go/src/github.com/docker/distribution
ENV BUILDTAGS include_oss include_gcs
ENV GO111MODULE auto

WORKDIR $DISTRIBUTION_DIR
COPY . $DISTRIBUTION_DIR
RUN apt update && apt install -y git
#RUN go mod tidy && CGO_ENABLED=0 make PREFIX=/go clean binaries
